var appFields = {
	"fields": {
		"aboutBundles": "bundles",
		"aboutClients": "clients",
		"aboutCompany": "company",
		"aboutEmail": "email",
		"aboutGroup": "group",
		"aboutJWT": "jwt",
		"aboutLoginName": "username",
		"aboutRole": "role",
		"aboutUserName": "name",
		"bundleCommand": "command",
		"bundleCommandVer": "version.cmd",
		"bundleConnector": "connector",
		"bundleId": "_id",
		"bundleName": "name",
		"bundleParameterVer": "version.prms",
		"commandId": "id",
		"commandName": "name",
		"commandService": "service",
		"commandCommandId": "id",
		"commandCommandText": "command",
		"commandCommandVersion": "version",
		"commandParametersId": "id",
		"commandParametersText": "parameters",
		"commandParametersVersion": "version",
		"companyId": "id",
		"companyName": "name",
		"companyGroupDesc": "groups.description",
		"companyGroupId": "id",
		"companyGroupName": "groups.name",
		"companyGroupPlan": "groups.plan",
		"connectorId": "id",
		"connectorName": "name",
		"connectorService": "service",
		"loginName": "username",
		"loginPassword": "password",
		"messageText": " ",
		"userBundles": "bundles",
		"userClients": "clients",
		"userCode": "code",
		"userEmail": "email",
		"userGroup": "group",
		"userId": "id",
		"userJWT": "jwt",
		"userName": "name",
		"userPassword": "password",
		"userRole": "role",
		"userUsername": "username"
	},
	"lists": {
		"bundleCommandList": true,
		"bundleConnectorList": true,
		"userGroupList": true,
		"userRoleList": true,
		"userBundlesList": true
	}
};
